FROM golang:1.19 as builder

LABEL maintainer="NJWS, Inc."

WORKDIR /src/

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /build/subscribe-bmc ./cmd/subscribe-bmc

FROM ubuntu:18.04

LABEL maintainer="NJWS, Inc."

RUN apt update && \
    apt install ca-certificates curl -y && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/subscribe-bmc /usr/bin/

RUN chmod +x /usr/bin/subscribe-bmc

CMD ["/usr/bin/subscribe-bmc" , "run"]
