FROM golang:1.19 as builder

LABEL maintainer="NJWS, Inc."

WORKDIR /src/

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /build/bmc-app ./cmd/bmc-app

FROM ubuntu:18.04

LABEL maintainer="NJWS, Inc."

RUN apt update && \
    apt install ca-certificates -y && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/bmc-app /usr/bin/

RUN chmod +x /usr/bin/bmc-app

CMD ["/usr/bin/bmc-app" , "run"]
