//
//  Copyright 2023 NJWS Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pbredfish/pbredfish.proto

package pbredfish

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url          string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UUID         string `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	SerialNumber string `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Name         string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress   string `protobuf:"bytes,6,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Model        string `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Vendor       string `protobuf:"bytes,8,opt,name=vendor,proto3" json:"vendor,omitempty"`
	PowerState   string `protobuf:"bytes,9,opt,name=power_state,json=powerState,proto3" json:"power_state,omitempty"`
	HealthStatus string `protobuf:"bytes,10,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	IndicatorLed string `protobuf:"bytes,11,opt,name=indicator_led,json=indicatorLed,proto3" json:"indicator_led,omitempty"`
	MinTemp      string `protobuf:"bytes,12,opt,name=min_temp,json=minTemp,proto3" json:"min_temp,omitempty"`
	MaxTemp      string `protobuf:"bytes,13,opt,name=max_temp,json=maxTemp,proto3" json:"max_temp,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbredfish_pbredfish_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_pbredfish_pbredfish_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_pbredfish_pbredfish_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Device) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Device) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Device) GetPowerState() string {
	if x != nil {
		return x.PowerState
	}
	return ""
}

func (x *Device) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *Device) GetIndicatorLed() string {
	if x != nil {
		return x.IndicatorLed
	}
	return ""
}

func (x *Device) GetMinTemp() string {
	if x != nil {
		return x.MinTemp
	}
	return ""
}

func (x *Device) GetMaxTemp() string {
	if x != nil {
		return x.MaxTemp
	}
	return ""
}

type Devices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Device `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Devices) Reset() {
	*x = Devices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbredfish_pbredfish_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_pbredfish_pbredfish_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_pbredfish_pbredfish_proto_rawDescGZIP(), []int{1}
}

func (x *Devices) GetItems() []*Device {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pbredfish_pbredfish_proto protoreflect.FileDescriptor

var file_pbredfish_pbredfish_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x62, 0x72, 0x65, 0x64, 0x66, 0x69, 0x73, 0x68, 0x2f, 0x70, 0x62, 0x72, 0x65,
	0x64, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x62, 0x6d, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73,
	0x64, 0x6b, 0x2e, 0x70, 0x62, 0x72, 0x65, 0x64, 0x66, 0x69, 0x73, 0x68, 0x22, 0xe7, 0x02, 0x0a,
	0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6c, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x65, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x6d,
	0x61, 0x78, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x61, 0x78, 0x54, 0x65, 0x6d, 0x70, 0x22, 0x48, 0x0a, 0x07, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x3d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x62, 0x6d, 0x63,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x62, 0x72, 0x65, 0x64, 0x66, 0x69,
	0x73, 0x68, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x6f, 0x6c, 0x69, 0x61, 0x67, 0x65, 0x63, 0x70, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x2d, 0x62, 0x6d, 0x63, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x70,
	0x62, 0x72, 0x65, 0x64, 0x66, 0x69, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbredfish_pbredfish_proto_rawDescOnce sync.Once
	file_pbredfish_pbredfish_proto_rawDescData = file_pbredfish_pbredfish_proto_rawDesc
)

func file_pbredfish_pbredfish_proto_rawDescGZIP() []byte {
	file_pbredfish_pbredfish_proto_rawDescOnce.Do(func() {
		file_pbredfish_pbredfish_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbredfish_pbredfish_proto_rawDescData)
	})
	return file_pbredfish_pbredfish_proto_rawDescData
}

var file_pbredfish_pbredfish_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbredfish_pbredfish_proto_goTypes = []interface{}{
	(*Device)(nil),  // 0: inventory.bmc.app.sdk.pbredfish.Device
	(*Devices)(nil), // 1: inventory.bmc.app.sdk.pbredfish.Devices
}
var file_pbredfish_pbredfish_proto_depIdxs = []int32{
	0, // 0: inventory.bmc.app.sdk.pbredfish.Devices.items:type_name -> inventory.bmc.app.sdk.pbredfish.Device
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pbredfish_pbredfish_proto_init() }
func file_pbredfish_pbredfish_proto_init() {
	if File_pbredfish_pbredfish_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbredfish_pbredfish_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbredfish_pbredfish_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Devices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbredfish_pbredfish_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbredfish_pbredfish_proto_goTypes,
		DependencyIndexes: file_pbredfish_pbredfish_proto_depIdxs,
		MessageInfos:      file_pbredfish_pbredfish_proto_msgTypes,
	}.Build()
	File_pbredfish_pbredfish_proto = out.File
	file_pbredfish_pbredfish_proto_rawDesc = nil
	file_pbredfish_pbredfish_proto_goTypes = nil
	file_pbredfish_pbredfish_proto_depIdxs = nil
}
